In [1]:
import kMeans

In [2]:
import numpy as np

In [4]:
reload(kMeans)
dataMat = np.mat(kMeans.loadDataSet('testSet.txt'))

In [5]:
dataMat.shape

(80L, 2L)

In [6]:
np.min(dataMat[:, 0])

-5.3797129999999997

In [7]:
np.min(dataMat[:, 1])

-4.2325860000000004

In [8]:
np.max(dataMat[:, 0])

4.8381379999999998

In [9]:
np.max(dataMat[:, 1])

5.1904000000000003

In [10]:
kMeans.randCent(dataMat, 2)

matrix([[-2.67160752, -1.78764592],
        [-4.32225348, -3.49961684]])

In [11]:
kMeans.distEclud(dataMat[0], dataMat[1])

5.184632816681332

In [12]:
dataMat[0]

matrix([[ 1.658985,  4.285136]])

In [13]:
reload(kMeans)

<module 'kMeans' from 'kMeans.pyc'>

In [14]:
myCentroids, clustAssing = kMeans.kMeans(dataMat, 4)

[[ 2.58472176  3.56710553]
 [-4.761136    1.41273909]
 [ 2.64853039 -1.6898028 ]
 [ 3.62252737  1.6494232 ]]
[[ 1.87380407  3.5460134 ]
 [-3.13265342 -0.01476825]
 [ 2.43385309 -2.85575373]
 [ 3.262091    2.073162  ]]
[[ 1.36683306  3.622562  ]
 [-3.18695357 -0.35938491]
 [ 2.65077367 -2.79019029]
 [ 3.21484275  2.1944465 ]]
[[ 0.77377313  3.57101044]
 [-3.26435785 -0.56399561]
 [ 2.65077367 -2.79019029]
 [ 3.1388135   2.441378  ]]
[[-0.56848347  3.34367493]
 [-3.43321524 -1.00773014]
 [ 2.65077367 -2.79019029]
 [ 2.942346    2.80047613]]
[[-2.15677217  3.03192211]
 [-3.4859745  -2.31300105]
 [ 2.65077367 -2.79019029]
 [ 2.71358074  3.11839563]]
[[-2.46154315  2.78737555]
 [-3.53973889 -2.89384326]
 [ 2.65077367 -2.79019029]
 [ 2.6265299   3.10868015]]


In [3]:
import matplotlib.pyplot as plt

In [25]:
dataMat3 = np.mat(kMeans.loadDataSet('testSet2.txt'))

In [29]:
reload(kMeans)

<module 'kMeans' from 'kMeans.py'>

In [30]:
centList, myNewAssments = kMeans.biKmeans(dataMat3, 3)

[[ 2.39928452  2.02271762]
 [-2.03991898  3.81987496]]
[[ 1.30897764  0.21151872]
 [-2.8815949   3.10812271]]
[[ 1.23710375  0.17480612]
 [-2.94737575  3.3263781 ]]
sseSplit, and notSplit :  570.722757425 0.0
the bestCentTopSplit is: 0
the len of bestClustAss is: 60
[[ 3.76038996  0.97167683]
 [-1.56896842 -1.65172123]]
[[ 2.93386365  3.12782785]
 [-0.45965615 -2.7782156 ]]
sseSplit, and notSplit :  68.6865481262 38.0629506357
[[-1.02021393  3.74499825]
 [-2.81004296  3.92193466]]
[[-1.391504    3.37801267]
 [-3.22194135  3.31726612]]
[[-1.76576557  3.39794014]
 [-3.58362738  3.28784469]]
sseSplit, and notSplit :  22.9717718963 532.659806789
the bestCentTopSplit is: 0
the len of bestClustAss is: 40
centList is: [matrix([[ 2.93386365,  3.12782785]]), [-2.94737575, 3.3263781000000003], [-0.45965614999999993, -2.7782156000000002]]


In [31]:
centList

matrix([[matrix([[ 2.93386365,  3.12782785]]),
         [-2.94737575, 3.3263781000000003],
         [-0.45965614999999993, -2.7782156000000002]]], dtype=object)

### 对地图上的点进行聚类

In [32]:
reload(kMeans)

<module 'kMeans' from 'kMeans.py'>

In [33]:
geoResults = kMeans.geoGrab('l VA Center', 'August, ME')

http://where.yahooapis.com/geocode?flags=J&location=l+VA+Center+August%2C+ME&appid=aaa0VN6k


IOError: [Errno socket error] [Errno 10060] 

In [34]:
geoResults

NameError: name 'geoResults' is not defined